# Generated by Django 2.0.8 on 2018-09-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180913_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticelist',
            name='link',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
