# Generated by Django 2.0.8 on 2018-09-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_noticelist_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='email',
            field=models.EmailField(blank=True, max_length=255, verbose_name='Email address'),
        ),
    ]
