# Generated by Django 2.0.8 on 2018-09-18 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0003_gallery_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='Photo',
            new_name='photo',
        ),
    ]
